// CubCrawl seed data — clubs, posts, alerts, people
const CLUBS = {
  ebd: {
    id: 'val',
    name: 'VALORANT @EaUCD',
    handle: '@DavisVal',
    school: 'University of California, Davis',
    bio: 'Official Valorant club @ UC Davis!',
    avatar: 'assets/valorant.png',
    tags: ['#tech', '#game'],
    members: 142,
    posts: 38,
    verified: false,
  },
  art: {
    id: 'art',
    name: 'Art Club',
    handle: '@ACDAVIS',
    school: 'University of California, Davis',
    bio: 'Open studio every Thursday. All mediums, all skill levels.',
    avatar: 'assets/avatar-11.png',
    tags: ['#art', '#painting', '#design'],
    members: 218,
    posts: 91,
  },
  pcg: {
    id: 'pcg',
    name: 'Pro College Gamers',
    handle: '@PCGDAVIS',
    school: 'University of California, Davis',
    bio: 'Davis\'s competitive esports community. Valorant, League, Apex.',
    avatar: 'assets/avatar-21.png',
    tags: ['#gaming', '#esports', '#valorant'],
    members: 312,
    posts: 156,
  },
  food: {
    id: 'food',
    name: 'Food Fundraiser Club',
    handle: '@FFCDAVIS',
    school: 'University of California, Davis',
    bio: 'Raising funds for local shelters, one bake sale at a time.',
    avatar: 'assets/avatar-23.png',
    tags: ['#service', '#community'],
    members: 87,
    posts: 24,
  },
  hack: {
    id: 'hack',
    name: 'HackDavis',
    handle: '@HACKDAVIS',
    school: 'University of California, Davis',
    bio: 'California\'s largest collegiate hackathon for social good.',
    avatar: 'assets/club-hackdavis.png',
    tags: ['#tech', '#hackathon', '#socialgood'],
    members: 540,
    posts: 47,
  },
  esports: {
    id: 'esports',
    name: 'Esports at UC Davis',
    handle: '@ESPORTSUCD',
    school: 'University of California, Davis',
    bio: 'Official UC Davis esports — varsity rosters and casual play.',
    avatar: 'assets/club-esports.png',
    tags: ['#gaming', '#varsity'],
    members: 421,
    posts: 88,
  },
  vsa: {
    id: 'vsa',
    name: 'VSA',
    handle: '@VSADAVIS',
    school: 'University of California, Davis',
    bio: 'Vietnamese Student Association — culture, community, and food.',
    avatar: 'assets/club-vsa.png',
    tags: ['#culture', '#community', '#food'],
    members: 198,
    posts: 62,
  },
  fit: {
    id: 'fit',
    name: 'Fitness Club',
    handle: '@FITUCD',
    school: 'University of California, Davis',
    bio: 'Group lifts, runs, and yoga. All bodies welcome.',
    avatar: 'assets/club-fitness.png',
    tags: ['#fitness', '#wellness'],
    members: 162,
    posts: 33,
  },
};

const POSTS = [
  {
    id: 'p1',
    clubId: 'art',
    handle: 'Art Club',
    sub: '@ACDAVIS',
    avatar: 'assets/avatar-11.png',
    time: '2h',
    body: "Hey! Everyone — join our Art Club open studio this Thursday at 6pm. Bring whatever you're working on, we'll provide the rest.",
    image: 'assets/post-artclub.png',
    likes: 124,
    comments: 8,
    tags: ['#art', '#painting'],
  },
  {
    id: 'p2',
    clubId: 'pcg',
    handle: 'Pro College Gamers',
    sub: '@PCGDAVIS',
    avatar: 'assets/avatar-21.png',
    time: '5h',
    body: "Wassup gamers! Looking for a 5-stack to take the Spring Valorant league. DM if you're plat+ and free Thursday nights.",
    likes: 15,
    comments: 4,
    tags: ['#gaming', '#valorant'],
  },
  {
    id: 'p3',
    clubId: 'pcg',
    handle: 'Pro College Gamer',
    sub: '@PCGDAVIS',
    avatar: 'assets/avatar-21.png',
    time: '1d',
    body: "I've created this awesome new game. Check it out and tell me what y'all think about it! Any feedback is greatly appreciated and would really help me out.\n\nVery Cool Game ↓",
    image: 'assets/post-gaming.png',
    likes: 9,
    comments: 2,
    tags: ['#gaming', '#indiedev'],
  },
  {
    id: 'p4',
    clubId: 'food',
    handle: 'Food Fundraiser Club',
    sub: '@FFCDAVIS',
    avatar: 'assets/avatar-23.png',
    time: '2d',
    body: "Help Needed for Our Food Fundraiser!\n\nOur club is hosting a food fundraiser to support local homeless shelters, and we would greatly appreciate your help. We are currently accepting donations of canned goods and other non-perishable food items to help provide meals for those in need.\n\nAny donation, big or small, can make a difference and help support members of our community facing hardship. Thank you for your kindness and support! Donate Now!",
    likes: 9,
    comments: 1,
    tags: ['#service', '#community'],
  },
  {
    id: 'p5',
    clubId: 'val',
    handle: 'VALORANT @EaUCD',
    sub: '@DavisVAL',
    avatar: 'assets/valorant.png',
    time: '3d',
    body: "Hey! Everyone come and learn more about the rich and vibrant culture and history of Valorant! 5pm at TLC 1020. Don't be late! :)",
    image: 'assets/brubhbuhrub.png',
    fullImage: true,
    likes: 47,
    comments: 12,
    tags: ['#gaming', '#tech'],
  },
];

const ALERTS = {
  today: [
    { id: 'a1', avatar: 'assets/avatar-21.png', text: 'Pro College Gamers just posted an event!', time: '12m', kind: 'event' },
    { id: 'a2', avatar: 'assets/avatar-11.png', text: 'Art Club liked your comment.', time: '1h', kind: 'like' },
    { id: 'a3', avatar: 'assets/club-hackdavis.png', text: 'HackDavis applications close in 3 days.', time: '3h', kind: 'reminder' },
  ],
  week: [
    { id: 'a4', avatar: 'assets/valorant.png', text: 'VALORANT @EaUCD posted a new event: TLC 1020.', time: '2d', kind: 'event' },
    { id: 'a5', avatar: 'assets/avatar-23.png', text: 'Food Fundraiser Club mentioned you.', time: '4d', kind: 'mention' },
    { id: 'a6', avatar: 'assets/club-vsa.png', text: 'VSA Lunar New Year — RSVPs open.', time: '5d', kind: 'event' },
  ],
  month: [
    { id: 'a7', avatar: 'assets/club-fitness.png', text: 'Fitness Club: 5K results posted.', time: '2w', kind: 'reminder' },
    { id: 'a8', avatar: 'assets/club-esports.png', text: 'Esports at UC Davis added a tournament.', time: '3w', kind: 'event' },
  ],
};

const ME = {
  name: 'bryan9',
  handle: '@bryan9',
  pronouns: 'He/Him/His',
  school: 'University of California, Davis',
  bio: "UCD '27, heh. Sometimes I dance, sometimes I code.",
  avatar: 'assets/profile-bryan.jpg',
  cover: 'assets/profile-cover.png',
  tags: ['#fitness', '#gaming', '#music'],
  myClubs: [
    { id: 'hack', role: 'Member' },
    { id: 'ebd', role: 'President' },
    { id: 'esports', role: 'Officer' },
    { id: 'vsa', role: 'Member' },
  ],
};

const TRENDING_TAGS = ['#dancing', '#hackathon', '#valorant', '#art', '#wellness', '#culture', '#service', '#indiedev'];

const EVENTS = [
  { id: 'e1', clubId: 'ebd', title: 'Belly Dance Workshop', when: 'Thu · 5:00 PM', where: 'TLC 1020' },
  { id: 'e2', clubId: 'hack', title: 'HackDavis Kickoff', when: 'Sat · 10:00 AM', where: 'ARC Pavilion' },
  { id: 'e3', clubId: 'art', title: 'Open Studio', when: 'Thu · 6:00 PM', where: 'Art Annex' },
];

window.CC_DATA = { CLUBS, POSTS, ALERTS, ME, TRENDING_TAGS, EVENTS };
